<a href="https://colab.research.google.com/github/kazarach/UAS_ML/blob/main/AutoGrad_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.randn(3, requires_grad=True)
y = x + 2
print(x)
print(y)
print(y.grad_fn)

tensor([-1.0163, -0.3668,  1.0395], requires_grad=True)
tensor([0.9837, 1.6332, 3.0395], grad_fn=<AddBackward0>)


In [ ]:
z = y * y * 3
print(z)
z = z.mean()
print(z)
z.backward()
print(x.grad)

tensor([ 2.9031,  8.0023, 27.7161], grad_fn=<MulBackward0>)
tensor(12.8738, grad_fn=<MeanBackward0>)
tensor([1.9674, 3.2665, 6.0790])


In [ ]:
x = torch.randn(3, requires_grad=True)
y = x * 2
for _ in range(10):
    y = y * 2

print(y)
print(y.shape)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)


tensor([330.3999, 373.0628, 257.8631], grad_fn=<MulBackward0>)
torch.Size([3])
tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [ ]:
a = torch.randn(2, 2)
print(a.requires_grad)
b = ((a * 3) / (a - 1))
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [ ]:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
b = a.detach()
print(b.requires_grad)
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
False
True
False


In [ ]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

    with torch.no_grad():
        weights -= 0.1 * weights.grad

    weights.grad.zero_()

print(weights)
print(model_output)

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
